build_for_android_osx:
  name: Build JNIBridge OSX (For Publishing)
  agent:
    type: Unity::VM::osx
    image: build-system/unity-extra-macos-10.13-katana:v0.3.6-621005
    flavor: b1.xlarge
  variables:
    ANDROID_SDK_ROOT: /Users/bokken/android-sdk_auto
  commands:
    - perl build.pl jnibridge
  artifacts:
    artifacts:
      paths:
        - build/builds.zip

build_for_android_win:
  name: Build JNIBridge Windows (For Local Development)
  agent:
    type: Unity::VM
    image: cds-ops/win10-base:stable
    flavor: b1.xlarge
  variables:
    ANDROID_SDK_ROOT: C:\Users\bokken\android-sdk_auto
  commands:
    - perl build.pl jnibridge
  artifacts:
    artifacts:
      paths:
        - build/builds.zip

test_on_osx:
  name: Test on OSX
  agent:
    type: Unity::VM::osx
    image: build-system/unity-extra-macos-10.13-katana:v0.3.6-621005
    flavor: b1.xlarge
  variables:
    ANDROID_SDK_ROOT: /Users/bokken/android-sdk_auto
  commands:
    - perl build.pl test

test_on_win:
  name: Test on Windows
  agent:
    type: Unity::VM
    image: cds-ops/win10-base:stable
    flavor: b1.xlarge
  variables:
    ANDROID_SDK_ROOT: /Users/bokken/android-sdk_auto
  commands:
    - perl build.pl test

test_trigger:
  name: Tests Trigger
  agent:
    type: Unity::VM::osx
    image: build-system/unity-extra-macos-10.13-katana:v0.3.6-621005
    flavor: b1.xlarge
  commands:
    - true
  triggers:
    branches:
      only:
        - "/.*/"
  dependencies:
    - .yamato/build.yml#build_for_android_osx
    - .yamato/build.yml#build_for_android_win
    - .yamato/build.yml#test_on_osx
    - .yamato/build.yml#test_on_win
